"""IEM HSA cohort deals in Teachworks: what the API does, what it cannot,
and the one task per gap that covers it (spec docs/specs/cohort-intake-spec.md
§5.5, §5.7; config `hsa:`).

deal_sync already creates the family and the student (Package billing via
charter_pipelines). Three things it cannot do through /v1 as of 2026-09-15:

1. ES as an ADDITIONAL CONTACT on the student, so she receives session notes.
   `tw.add_additional_contact` is the spike: on success it is recorded, on
   any failure ONE task goes to the deal owner (never silently dropped).
2. The $0/hr service, the per-student allocation (= [Agent] HSA Sessions) and
   the ONE flat invoice per group to IEM, sent upfront. The API cannot create
   invoices (po_inbox has said so since August), so this is ONE task per
   group to charter_admin, summed from the sibling deals' amounts and keyed
   on [Agent] HSA Group. Never one task per deal.
3. The lesson series. The scheduler books it; LOCKED (Roman 9/15): no lesson
   on a no-class date, and the count must equal the cohort's sessions.
   verify_lessons() reads the booked series back and flags the owner + sales
   once a day while it is wrong. The calendar itself is generated by
   agents/cohort_intake/cohort.py, the single source for every dated list.

Deterministic: no reasoning, no CARE pointer.
"""
from __future__ import annotations

import sys
from datetime import date, datetime, timedelta

from . import audit, hubspot_client as hs, slack_client, teachworks_client as tw
from .business_hours import add_business_hours, now_la
from .config import ROOT, cfg, staff

# agents/cohort_intake/cohort.py is the calendar's source of truth; the repo
# root is one level above the email package.
if str(ROOT.parent) not in sys.path:
    sys.path.insert(0, str(ROOT.parent))

DEAL_PROPS = ["dealname", "amount", "hubspot_owner_id", "student_first_name",
              "teacher_of_record_name", "teacher_of_record_email", "parent_email",
              "hsa_cohort", "hsa_group", "hsa_sessions", "hsa_start", "hsa_slot",
              "date_of_last_lesson_in_this_deal"]


def _hc() -> dict:
    return cfg().get("hsa") or {}


def _deal_url(deal_id: str) -> str:
    portal = (cfg().get("hubspot") or {}).get("portal_id", "6312752")
    return f"https://app.hubspot.com/contacts/{portal}/record/0-3/{deal_id}"


def _fetch_props(deal_id: str) -> dict:
    got = hs._get(f"/crm/v3/objects/deals/{deal_id}", {"properties": ",".join(DEAL_PROPS)})
    return (got or {}).get("properties") or {} if isinstance(got, dict) else {}


def _due_ms(hours: float = 8) -> int:
    return int(add_business_hours(now_la(), hours).timestamp() * 1000)


def _invoice_owner(p: dict) -> tuple[str | None, str]:
    """(HubSpot owner id, label) for the invoice/allocation tasks. Roman
    2026-09-16: the SCHEDULERS create the Teachworks invoices, so the default
    `invoice_owner: deal_owner` routes to whoever owns the deal (the group's
    scheduler by parity). Any staff/role key still works for a different seat."""
    who = str(_hc().get("invoice_owner") or "deal_owner")
    if who == "deal_owner":
        return (str(p.get("hubspot_owner_id") or "") or None), "deal_owner"
    rec = staff(who) or {}
    return (str(rec.get("hubspot_owner_id") or "") or None), who


def _split_name(full: str) -> tuple[str, str]:
    parts = [x for x in (full or "").strip().split() if x]
    if not parts:
        return "", ""
    return parts[0], " ".join(parts[1:])


# ── 1. ES as additional contact ──────────────────────────────────────────────

def _tor_additional_contact(deal: dict, p: dict, record: dict, token: str) -> None:
    key = f"hsa-tor-contact:{deal['id']}"
    if audit.already_processed(key):
        return
    tor_email = (p.get("teacher_of_record_email") or "").strip().lower()
    tor_name = (p.get("teacher_of_record_name") or "").strip()
    student = (p.get("student_first_name") or "").strip() or "the student"
    if not tor_email:
        return
    cust = record.get("tw_customer_id")
    ok, detail = False, "no Teachworks customer id on this sync"
    if cust not in (None, "DRYRUN"):
        first, last = _split_name(tor_name)
        ok, detail = tw.add_additional_contact(
            cust, {"customer_id": cust, "first_name": first or tor_name, "last_name": last,
                   "email": tor_email, "receive_lesson_notes": True}, token)
    if ok:
        audit.append({"message_id": key, "source": "hsa_sync", "deal_id": deal["id"],
                      "action_taken": "hsa_tor_contact_added", "tor_email": tor_email,
                      "detail": detail})
        record["hsa_tor_contact"] = "api"
        print(f"  🧑‍🏫 ES {tor_email} added as additional contact ({detail})")
        return
    owner_id = p.get("hubspot_owner_id")
    body = (f"Teachworks could not add the ES as an additional contact through the API "
            f"({detail}). Add her by hand so she receives session notes:\n"
            f"Student: {student}\nES: {tor_name} <{tor_email}>\n"
            f"Family (Teachworks customer id): {cust}\n"
            f"HubSpot deal: {_deal_url(deal['id'])}")
    hs.create_task(f"Add ES {tor_name or tor_email} as additional contact in Teachworks — {student}",
                   body, owner_id, _due_ms(8), priority="MEDIUM")
    audit.append({"message_id": key, "source": "hsa_sync", "deal_id": deal["id"],
                  "action_taken": "hsa_tor_contact_task", "tor_email": tor_email,
                  "detail": detail, "owner_id": owner_id})
    record["hsa_tor_contact"] = "task"
    print(f"  📋 ES additional-contact task for deal owner ({detail})")


# ── 2. One flat invoice per group ────────────────────────────────────────────

def _group_invoice_task(deal: dict, p: dict, record: dict) -> None:
    hc = _hc()
    group = (p.get("hsa_group") or "").strip()
    if not group:
        return
    key = f"hsa-invoice:{group}"
    if audit.already_processed(key):
        return
    sibs = hs._search_all("/crm/v3/objects/deals/search", [
        {"propertyName": "pipeline", "operator": "EQ", "value": hc.get("pipeline", "5119061")},
        {"propertyName": hc.get("group_prop", "hsa_group"), "operator": "EQ", "value": group},
    ], ["dealname", "amount", "student_first_name", "hsa_sessions", "hsa_slot", "hsa_start",
        "teacher_of_record_name"])
    if not sibs:
        sibs = [deal]
    total = 0.0
    lines = []
    for s in sibs:
        sp = s.get("properties") or {}
        try:
            amt = float(sp.get("amount") or 0)
        except (TypeError, ValueError):
            amt = 0.0
        total += amt
        lines.append(f"  - {sp.get('dealname') or s.get('id')}: ${amt:,.2f} "
                     f"({sp.get('hsa_sessions') or '?'} sessions) {_deal_url(str(s.get('id')))}")
    sessions = (p.get("hsa_sessions") or "?")
    owner_id, owner_label = _invoice_owner(p)
    body = (f"IEM HSA group {group}: one flat invoice to IEM (Angie Covil, acovil@ieminc.org), "
            f"sent upfront. Total = sum of the {len(sibs)} sibling deal amounts = ${total:,.2f} "
            f"({sessions} sessions x $150).\n\nIn Teachworks:\n"
            f"1. Each student below: service 'IEM HSA group' at $0/hr, package allocation "
            f"{sessions} hours (hours tracked per student, billed to IEM flat).\n"
            f"2. ONE invoice to IEM for ${total:,.2f} covering the whole group (not per student). "
            f"The $0 tracking invoices per student are ignored by the invoice sweep.\n\n"
            f"Deals in this group:\n" + "\n".join(lines) +
            f"\n\nSlot: {p.get('hsa_slot') or '?'} from {p.get('hsa_start') or '?'}. "
            f"ES: {p.get('teacher_of_record_name') or '?'}.")
    hs.create_task(f"HSA group invoice — {group} (${total:,.2f}, {len(sibs)} students)", body,
                   owner_id, _due_ms(8), priority="HIGH")
    audit.append({"message_id": key, "source": "hsa_sync", "action_taken": "hsa_group_invoice_task",
                  "group": group, "total": round(total, 2), "deal_ids": [str(s.get("id")) for s in sibs],
                  "owner": owner_label, "owner_id": owner_id})
    record["hsa_group_invoice_task"] = group
    print(f"  🧾 HSA group invoice task for {group}: ${total:,.2f} over {len(sibs)} deal(s)")


def after_sync(deal: dict, record: dict, contact: dict | None, token: str) -> None:
    """Called by deal_sync.sync_deal right after the family/student write for
    any deal carrying [Agent] HSA Sessions."""
    if not _hc().get("enabled", True):
        return
    p = dict(deal.get("properties") or {})
    p.update({k: v for k, v in _fetch_props(deal["id"]).items() if v not in (None, "")})
    _tor_additional_contact(deal, p, record, token)
    _group_invoice_task(deal, p, record)


# ── 2b. Late adds: the group's invoice task was written before this deal ──

def _invoiced_deal_ids(group: str) -> set[str] | None:
    """Deal ids the group's invoice task covered, or None when no task yet."""
    found = None
    for r in audit._iter_records():
        if r.get("action_taken") == "hsa_group_invoice_task" and r.get("group") == group:
            found = set(str(x) for x in (r.get("deal_ids") or []))
        elif r.get("action_taken") == "hsa_late_add_task" and r.get("group") == group and found is not None:
            found.add(str(r.get("deal_id")))
    return found


def late_add_sweep() -> None:
    """A cohort deal created AFTER its group's invoice task (Aster White,
    2026-09-16 18:18 PT) is invisible to Kath: the task lists the students it
    was written with. Every run, any HSA deal missing from its group's
    invoice record gets ONE late-add task to the invoice owner (service +
    allocation for that student; the flat total does not change)."""
    hc = _hc()
    if not hc.get("enabled", True):
        return
    deals = hs._search_all("/crm/v3/objects/deals/search", [
        {"propertyName": "pipeline", "operator": "EQ", "value": hc.get("pipeline", "5119061")},
        {"propertyName": hc.get("group_prop", "hsa_group"), "operator": "HAS_PROPERTY"},
    ], DEAL_PROPS)
    covered: dict[str, set[str] | None] = {}
    made = 0
    for d in deals:
        did = str(d["id"])
        p = d.get("properties") or {}
        group = (p.get("hsa_group") or "").strip()
        if not group:
            continue
        key = f"hsa-invoice-late:{group}:{did}"
        if audit.already_processed(key):
            continue
        if group not in covered:
            covered[group] = _invoiced_deal_ids(group)
        ids = covered[group]
        if ids is None or did in ids:
            continue                  # no invoice task yet (after_sync makes it), or already listed
        student = (p.get("student_first_name") or "").strip() or p.get("dealname") or did
        body = (f"Late add to IEM HSA group {group}: {student} joined after the group invoice task "
                f"was written. In Teachworks: service 'IEM HSA group' at $0/hr and a package "
                f"allocation of {p.get('hsa_sessions') or '?'} hours for this student. The flat "
                f"group invoice total does not change (${150 * int(float(p.get('hsa_sessions') or 0)):,.2f} "
                f"for the group); the sibling deals were re-split.\n"
                f"Slot: {p.get('hsa_slot') or '?'} from {p.get('hsa_start') or '?'}. "
                f"ES: {p.get('teacher_of_record_name') or '?'}.\n{_deal_url(did)}")
        owner_id, owner_label = _invoice_owner(p)
        hs.create_task(f"HSA late add — {student} joined {group}: set up service + allocation",
                       body, owner_id, _due_ms(8), priority="HIGH")
        audit.append({"message_id": key, "source": "hsa_sync", "action_taken": "hsa_late_add_task",
                      "group": group, "deal_id": did, "student": student,
                      "owner": owner_label, "owner_id": owner_id})
        made += 1
    if made:
        print(f"hsa late_add_sweep: {made} late-add task(s)")


# ── 3. Lesson-series verification ────────────────────────────────────────────

def _student_lessons(parent_email: str, student_first: str, start: date) -> list[date]:
    """Dates of the student's booked, not-cancelled lessons from `start`,
    across both Teachworks accounts."""
    out: list[date] = []
    sf = (student_first or "").strip().lower()
    for token in tw.accounts().values():
        for cust in tw.tw_get("customers", {"email": (parent_email or "").strip().lower()}, token=token):
            for s in tw.tw_get("students", {"customer_id": cust.get("id")}, token=token):
                if sf and (s.get("first_name") or "").strip().lower() != sf:
                    continue
                for les in tw.tw_get("lessons", {"student_id": s["id"],
                                                 "from_date[gte]": start.isoformat()}, token=token):
                    if "cancel" in str(les.get("status", "")).lower():
                        continue
                    d = tw._safe_date(les.get("from_date"))
                    if d:
                        out.append(date.fromisoformat(d[:10]))
    return sorted(set(out))


def verify_lessons() -> None:
    hc = _hc()
    if not hc.get("enabled", True):
        return
    from agents.cohort_intake import cohort as C  # noqa: E402 — repo root on sys.path above
    today = now_la().date()
    horizon = today - timedelta(days=int(hc.get("lesson_check_days", 60)))
    since_ms = int(datetime.combine(horizon, datetime.min.time()).timestamp() * 1000)
    deals = hs._search_all("/crm/v3/objects/deals/search", [
        {"propertyName": "pipeline", "operator": "EQ", "value": hc.get("pipeline", "5119061")},
        {"propertyName": hc.get("sessions_prop", "hsa_sessions"), "operator": "HAS_PROPERTY"},
        {"propertyName": "hsa_start", "operator": "GTE", "value": str(since_ms)},
    ], DEAL_PROPS)
    checked = flagged = 0
    for d in deals:
        did = str(d["id"])
        if audit.already_processed(f"hsa-lessons-ok:{did}"):
            continue
        p = d.get("properties") or {}
        try:
            expected = int(float(p.get("hsa_sessions") or 0))
            start = date.fromisoformat((p.get("hsa_start") or "")[:10])
        except ValueError:
            continue
        lessons = _student_lessons(p.get("parent_email") or "", p.get("student_first_name") or "", start)
        if not lessons:
            continue                      # not booked yet: nothing to verify
        checked += 1
        bad = [x for x in lessons if C.is_no_class(x)]
        if len(lessons) == expected and not bad:
            audit.append({"message_id": f"hsa-lessons-ok:{did}", "source": "hsa_sync",
                          "action_taken": "hsa_lessons_verified", "deal_id": did,
                          "count": len(lessons), "first": lessons[0].isoformat(),
                          "last": lessons[-1].isoformat()})
            print(f"  ✅ {p.get('dealname')}: {len(lessons)} lessons, none on a no-class date")
            continue
        flag_key = f"hsa-lessons-flag:{did}:{today.isoformat()}"
        if audit.already_processed(flag_key):
            continue
        flagged += 1
        problems = []
        if len(lessons) != expected:
            problems.append(f"{len(lessons)} lessons booked, cohort has {expected}")
        if bad:
            problems.append("on no-class dates: " + ", ".join(f"{x:%b %-d}" for x in bad))
        text = (f"⚠️ HSA lesson series check: *{p.get('dealname')}*: " + "; ".join(problems) +
                f". Skip dates: {C.no_class_text()}. Fix the series in Teachworks. "
                f"{_deal_url(did)}")
        targets = []
        owner_id = str(p.get("hubspot_owner_id") or "")
        for rec in (cfg().get("staff") or {}).values():
            if str(rec.get("hubspot_owner_id") or "") == owner_id and rec.get("slack_user_id"):
                targets.append(rec["slack_user_id"])
        for seat in hc.get("flag_to") or []:
            uid = (staff(seat) or {}).get("slack_user_id")
            if uid and uid not in targets:
                targets.append(uid)
        for uid in targets:
            slack_client.dm(uid, text)
        audit.append({"message_id": flag_key, "source": "hsa_sync", "action_taken": "hsa_lessons_flagged",
                      "deal_id": did, "problems": problems, "notified": targets})
    if checked or flagged:
        print(f"hsa verify_lessons: {checked} checked, {flagged} flagged")
